---
title: Saxula Brass Band
author: Tiziano Colagrossi
email: saxulabrassband@gmail.com
description: |-
  La Saxula Brass Band è un gruppo musicale composto da circa 25/30 elementi.
  Nasce a San Gregorio da Sassola nel 1998 per iniziativa di alcuni ragazzi desiderosi di approfondire i vari aspetti  e le diverse forme musicali.
baseurl: "/saxula"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
